# Generated by Django 5.0.1 on 2024-02-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='text_here',
            new_name='text',
        ),
    ]
