# Generated by Django 5.0.1 on 2024-02-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_paragraph_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='pic',
            new_name='pics',
        ),
    ]
