# Generated by Django 5.0.1 on 2024-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_pic_paragraph_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('h5', models.CharField(max_length=100)),
            ],
        ),
    ]
